# Generated by Django 5.0 on 2023-12-12 16:10

import project.main.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=5,
                validators=[project.main.models.validate_more_than_zero],
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="archived",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="type",
            field=models.CharField(
                choices=[
                    ("BILL", "Bill"),
                    ("SAVING", "Saving"),
                    ("TRANSFER", "Transfer"),
                ],
                max_length=20,
            ),
        ),
    ]
